// البيانات الافتراضية الأولية لمنظومة مخازن الهيئة العامة لخدمات نقل الدم
import {
  Item,
  ReceivingVoucher,
  IssueVoucher,
  DamagedItemRecord,
  Supplier,
  BeneficiaryEntity,
  User,
  Warehouse,
} from '@/types';

// =============================================
// 1. المخازن المعتمدة
// =============================================
export const initialWarehouses: Warehouse[] = [
  {
    Id: 1,
    Name: 'المخزن الرئيسي المركز - طرابلس',
    Code: 'WH-001',
    Location: 'طرابلس - المقر الرئيسي للهيئة',
    Type: 'رئيسي',
    ManagerName: 'أمين المخزن الرئيسي',
    Description: 'المخزن المركزي لتخزين أكياس الدم والكواشف والمستلزمات الطبية',
    IsActive: true,
    CreatedAt: '2026-01-01',
    TotalStock: 14200,
  },
  {
    Id: 2,
    Name: 'مخزن المركز الإقليمي - بنغازي',
    Code: 'WH-002',
    Location: 'بنغازي - منطقة الهواري',
    Type: 'إقليمي / فرعي',
    ManagerName: 'أحمد محمد',
    Description: 'مخزن المنطقة الشرقية لبنوك الدم',
    IsActive: true,
    CreatedAt: '2026-01-15',
    TotalStock: 5800,
  },
  {
    Id: 3,
    Name: 'مخزن المركز الإقليمي - مصراتة',
    Code: 'WH-003',
    Location: 'مصراتة - المركز الصحي',
    Type: 'إقليمي / فرعي',
    ManagerName: 'فاطمة علي',
    Description: 'مخزن المنطقة الوسطى لبنوك الدم',
    IsActive: true,
    CreatedAt: '2026-02-01',
    TotalStock: 4200,
  },
  {
    Id: 4,
    Name: 'مخزن مركز سبها الطبي',
    Code: 'WH-004',
    Location: 'سبها - المنطقة الجنوبية',
    Type: 'إقليمي / فرعي',
    ManagerName: 'صالح الورفلي',
    Description: 'مخزن المنطقة الجنوبية لبنوك الدم',
    IsActive: true,
    CreatedAt: '2026-03-01',
    TotalStock: 2100,
  },
];

// =============================================
// 2. قائمة الجهات المستفيدة (مصارف الدم والمستشفيات)
// =============================================
export const initialBeneficiaries: BeneficiaryEntity[] = [
  {
    Id: 1,
    Name: 'مصرف الدم المركزي - طرابلس (طريق الشط)',
    Code: 'BB-TRIP-01',
    City: 'طرابلس',
    DelegateName: 'طارق عبد السلام الزنتاني',
    DelegatePhone: '0913344556',
    DelegateIdNumber: '119850234190',
    Address: 'طريق الشط، طرابلس',
    Type: 'مصرف دم مركزي',
  },
  {
    Id: 2,
    Name: 'مصرف الدم الإقليمي - بنغازي',
    Code: 'BB-BEN-02',
    City: 'بنغازي',
    DelegateName: 'فرج محمود البرعصي',
    DelegatePhone: '0925566778',
    DelegateIdNumber: '119820123987',
    Address: 'شارع جمال عبد الناصر، بنغازي',
    Type: 'مصرف دم مركزي',
  },
  {
    Id: 3,
    Name: 'مصرف الدم المركزي - مصراتة',
    Code: 'BB-MIS-03',
    City: 'مصراتة',
    DelegateName: 'عبد الله الهادي الكواش',
    DelegatePhone: '0917788990',
    DelegateIdNumber: '119900345612',
    Address: 'المجمع الصحي، مصراتة',
    Type: 'مصرف دم مركزي',
  },
  {
    Id: 4,
    Name: 'بنك الدم - مستشفى طرابلس المركزي (شارع الزاوية)',
    Code: 'BB-TRIP-HOSP',
    City: 'طرابلس',
    DelegateName: 'د. خالد فرج المهدي',
    DelegatePhone: '0924455667',
    DelegateIdNumber: '119780456123',
    Address: 'شارع الزاوية، طرابلس',
    Type: 'مستشفى عام',
  },
  {
    Id: 5,
    Name: 'بنك الدم - مركز سبها الطبي',
    Code: 'BB-SEB-04',
    City: 'سبها',
    DelegateName: 'مفتاح أحمد السليماني',
    DelegatePhone: '0919988776',
    DelegateIdNumber: '119840567890',
    Address: 'مركز سبها الطبي، سبها',
    Type: 'بنك دم فرعي',
  },
  {
    Id: 6,
    Name: 'بنك الدم - مستشفى الزاوية التعليمي',
    Code: 'BB-ZAW-05',
    City: 'الزاوية',
    DelegateName: 'مصطفى حسين القمودي',
    DelegatePhone: '0923322110',
    DelegateIdNumber: '119890678901',
    Address: 'وسط مدينة الزاوية',
    Type: 'مستشفى عام',
  },
];

// =============================================
// 3. قائمة الموردين
// =============================================
export const initialSuppliers: Supplier[] = [
  {
    Id: 1,
    Name: 'شركة تيرومو الدولية (Terumo BCT)',
    Code: 'SUP-TRM-01',
    ContactPerson: 'م. حسام الدين الطرابلسي',
    Phone: '0912233445',
    Email: 'terumo.libya@terumobct.com',
    Address: 'طرابلس - برج الفاتح',
    Category: 'أكياس الدم والمستهلكات',
    IsActive: true,
    CreatedAt: '2026-01-01',
    UpdatedAt: '2026-07-20',
  },
  {
    Id: 2,
    Name: 'شركة فريزينيوس كابي (Fresenius Kabi)',
    Code: 'SUP-FRS-02',
    ContactPerson: 'د. عادل القرقني',
    Phone: '0923344556',
    Email: 'libya.office@fresenius-kabi.com',
    Address: 'طرابلس - قرقارش',
    Category: 'أكياس الدم وأجهزة الفصل',
    IsActive: true,
    CreatedAt: '2026-01-10',
    UpdatedAt: '2026-06-15',
  },
  {
    Id: 3,
    Name: 'شركة بيوتست الطبية (Biotest Medical)',
    Code: 'SUP-BIO-03',
    ContactPerson: 'د. سامي المبروك',
    Phone: '0914455667',
    Email: 'info@biotest-med.ly',
    Address: 'بنغازي - طريق المطار',
    Category: 'الكواشف والأمصال المخبرية',
    IsActive: true,
    CreatedAt: '2026-01-20',
    UpdatedAt: '2026-07-10',
  },
  {
    Id: 4,
    Name: 'شركة ميرك للأدوية والكواشف (Merck Healthcare)',
    Code: 'SUP-MRK-04',
    ContactPerson: 'م. مروان الترهوني',
    Phone: '0926677889',
    Email: 'merck.rep@pharma-libya.ly',
    Address: 'طرابلس - النوفليين',
    Category: 'الكواشف ومحاليل المطابقة',
    IsActive: true,
    CreatedAt: '2026-02-01',
    UpdatedAt: '2026-08-01',
  },
  {
    Id: 5,
    Name: 'شركة بكتون ديكنسون (Becton Dickinson)',
    Code: 'SUP-BD-05',
    ContactPerson: 'أ. ناصر الساعدي',
    Phone: '0918899001',
    Email: 'contact@bd-libya.ly',
    Address: 'مصراتة - المنطقة الصناعية',
    Category: 'المستلزمات الطبية وإبر السحب',
    IsActive: true,
    CreatedAt: '2026-02-15',
    UpdatedAt: '2026-07-28',
  },
];

// =============================================
// 4. قائمة الأصناف الطبية والمخزنية
// =============================================
export const initialItems: Item[] = [
  {
    Id: 1,
    Code: 'ITM-001',
    Name: 'أكياس دم مفردة 450ml مع محلول CPDA-1',
    Barcode: '6221001000014',
    Category: 'أكياس الدم',
    Unit: 'كيس',
    StorageType: 'ثلاجة',
    StorageLocation: 'ثلاجة حفظ أكياس الدم #1 - الرف A',
    SupplierId: 1,
    SupplierName: 'شركة تيرومو الدولية (Terumo BCT)',
    ActualStock: 2300,
    DamagedStock: 12,
    UnitPrice: 15.50,
    Status: 'متوفر',
    Description: 'أكياس جمع دم معقمة مفردة سعة 450 مل مزودة بمانع تجلط CPDA-1',
    IsActive: true,
    CreatedAt: '2026-01-05',
    UpdatedAt: '2026-08-10',
  },
  {
    Id: 2,
    Code: 'ITM-002',
    Name: 'أكياس دم مزدوجة 450ml مع محلول حفظ SAGM',
    Barcode: '6221001000021',
    Category: 'أكياس الدم',
    Unit: 'كيس',
    StorageType: 'ثلاجة',
    StorageLocation: 'ثلاجة حفظ أكياس الدم #2 - الرف B',
    SupplierId: 2,
    SupplierName: 'شركة فريزينيوس كابي (Fresenius Kabi)',
    ActualStock: 1100,
    DamagedStock: 5,
    UnitPrice: 22.00,
    Status: 'متوفر',
    Description: 'أكياس دم مزدوجة لفصل البلازما وكريات الدم الحمراء',
    IsActive: true,
    CreatedAt: '2026-01-05',
    UpdatedAt: '2026-08-12',
  },
  {
    Id: 3,
    Code: 'ITM-003',
    Name: 'أكياس دم ثلاثية 450ml لفصل الصفائح الدموية',
    Barcode: '6221001000038',
    Category: 'أكياس الدم',
    Unit: 'كيس',
    StorageType: 'ثلاجة',
    StorageLocation: 'ثلاجة حفظ أكياس الدم #2 - الرف C',
    SupplierId: 2,
    SupplierName: 'شركة فريزينيوس كابي (Fresenius Kabi)',
    ActualStock: 400,
    DamagedStock: 0,
    UnitPrice: 28.50,
    Status: 'متوفر',
    Description: 'أكياس ثلاثية مجهزة لإنتاج الصفائح الدموية والبلازما الطازجة المجمدة',
    IsActive: true,
    CreatedAt: '2026-01-08',
    UpdatedAt: '2026-08-15',
  },
  {
    Id: 4,
    Code: 'ITM-004',
    Name: 'كاشف فصيلة الدم Anti-A Monoclonal 10ml',
    Barcode: '6221001000045',
    Category: 'الكواشف والمحاليل',
    Unit: 'زجاجة',
    StorageType: 'ثلاجة',
    StorageLocation: 'ثلاجة الكواشف والمحاليل #1 - الرف 2 (2-8°C)',
    SupplierId: 3,
    SupplierName: 'شركة بيوتست الطبية (Biotest Medical)',
    ActualStock: 185,
    DamagedStock: 3,
    UnitPrice: 45.00,
    Status: 'متوفر',
    Description: 'كاشف مونوكلونال معتمد لتحديد فصيلة الدم A',
    IsActive: true,
    CreatedAt: '2026-01-10',
    UpdatedAt: '2026-08-18',
  },
  {
    Id: 5,
    Code: 'ITM-005',
    Name: 'كاشف فصيلة الدم Anti-B Monoclonal 10ml',
    Barcode: '6221001000052',
    Category: 'الكواشف والمحاليل',
    Unit: 'زجاجة',
    StorageType: 'ثلاجة',
    StorageLocation: 'ثلاجة الكواشف والمحاليل #1 - الرف 2 (2-8°C)',
    SupplierId: 3,
    SupplierName: 'شركة بيوتست الطبية (Biotest Medical)',
    ActualStock: 130,
    DamagedStock: 2,
    UnitPrice: 45.00,
    Status: 'متوفر',
    Description: 'كاشف مونوكلونال معتمد لتحديد فصيلة الدم B',
    IsActive: true,
    CreatedAt: '2026-01-10',
    UpdatedAt: '2026-08-18',
  },
  {
    Id: 6,
    Code: 'ITM-006',
    Name: 'كاشف العامل الريزيسي Anti-D (Rh) Monoclonal/Polyclonal 10ml',
    Barcode: '6221001000069',
    Category: 'الكواشف والمحاليل',
    Unit: 'زجاجة',
    StorageType: 'ثلاجة',
    StorageLocation: 'ثلاجة الكواشف والمحاليل #2 - الرف 1',
    SupplierId: 4,
    SupplierName: 'شركة ميرك للأدوية والكواشف (Merck Healthcare)',
    ActualStock: 90,
    DamagedStock: 0,
    UnitPrice: 48.00,
    Status: 'متوفر',
    Description: 'كاشف لتحديد العامل الريزيسي موجب أو سالب',
    IsActive: true,
    CreatedAt: '2026-01-12',
    UpdatedAt: '2026-08-20',
  },
  {
    Id: 7,
    Code: 'ITM-007',
    Name: 'إبر سحب دم معقمة 16G مزودة بصمام أمان',
    Barcode: '6221001000076',
    Category: 'المستلزمات الطبية',
    Unit: 'صندوق',
    StorageType: 'مخزن',
    StorageLocation: 'مخزن المستلزمات الجافة - الممر 3 - الرف C',
    SupplierId: 5,
    SupplierName: 'شركة بكتون ديكنسون (Becton Dickinson)',
    ActualStock: 4800,
    DamagedStock: 20,
    UnitPrice: 8.50,
    Status: 'متوفر',
    Description: 'إبر معقمة مخصصة لعمليات التبرع بالدم آمنة وسريعة التدفق',
    IsActive: true,
    CreatedAt: '2026-01-15',
    UpdatedAt: '2026-08-21',
  },
  {
    Id: 8,
    Code: 'ITM-008',
    Name: 'قفازات طبية لاتكس معقمة بدون بودرة M (100 قطعة)',
    Barcode: '6221001000083',
    Category: 'مستلزمات السلامة',
    Unit: 'علبة',
    StorageType: 'مخزن',
    StorageLocation: 'مخزن الوقاية والسلامة - الممر 1 - الرف A',
    SupplierId: 5,
    SupplierName: 'شركة بكتون ديكنسون (Becton Dickinson)',
    ActualStock: 2800,
    DamagedStock: 0,
    UnitPrice: 12.00,
    Status: 'متوفر',
    Description: 'قفازات فحص طبية خالية من البودرة عالية الجودة',
    IsActive: true,
    CreatedAt: '2026-01-20',
    UpdatedAt: '2026-08-22',
  },
  {
    Id: 9,
    Code: 'ITM-009',
    Name: 'أنابيب فحص الدم مع مانع تجلط EDTA K3 (100 أنبوب)',
    Barcode: '6221001000090',
    Category: 'المواد المخبرية',
    Unit: 'صندوق',
    StorageType: 'مخزن',
    StorageLocation: 'مخزن الفحوصات المخبرية - الممر 2 - الرف B',
    SupplierId: 5,
    SupplierName: 'شركة بكتون ديكنسون (Becton Dickinson)',
    ActualStock: 500,
    DamagedStock: 8,
    UnitPrice: 18.00,
    Status: 'متوفر',
    Description: 'أنابيب عينات لفحوصات الدم الشامل ومطابقة الفصائل',
    IsActive: true,
    CreatedAt: '2026-01-25',
    UpdatedAt: '2026-08-23',
  },
  {
    Id: 10,
    Code: 'ITM-010',
    Name: 'محلول ملحي معقم Saline 0.9% 500ml',
    Barcode: '6221001000106',
    Category: 'أدوية',
    Unit: 'زجاجة',
    StorageType: 'مخزن',
    StorageLocation: 'مخزن المحاليل والأدوية - الممر 4 - الرف D',
    SupplierId: 4,
    SupplierName: 'شركة ميرك للأدوية والكواشف (Merck Healthcare)',
    ActualStock: 0,
    DamagedStock: 15,
    UnitPrice: 5.50,
    Status: 'غير متوفر',
    Description: 'محلول كلوريد الصوديوم المعقم لغسيل كريات الدم والمطابقة',
    IsActive: true,
    CreatedAt: '2026-01-28',
    UpdatedAt: '2026-08-24',
  },
];

// =============================================
// 5. قائمة أذونات الاستلام (الوارد)
// =============================================
export const initialReceivingVouchers: ReceivingVoucher[] = [
  {
    Id: 1,
    VoucherNumber: 'REC-2026-0001',
    PoNumber: 'PO-2026-9041',
    Date: '2026-07-20',
    Warehouse: 'المخزن الرئيسي المركز - طرابلس',
    SupplierName: 'شركة تيرومو الدولية (Terumo BCT)',
    SupplierCode: 'SUP-TRM-01',
    DelegateName: 'سالم عبد الله الورفلي',
    DelegatePhone: '0912233990',
    DelegateIdNumber: '119860124578',
    StorekeeperName: 'أحمد محمد - أمين الخزينة',
    StorekeeperSignature: true,
    TotalQuantity: 3000,
    Notes: 'تم استلام الشحنة بحالة ممتازة ومطابقة للمواصفات القياسية وحفظها مباشرة بالثلاجة',
    Status: 'معتمد',
    CreatedAt: '2026-07-20 10:30',
    Items: [
      {
        ItemCode: 'ITM-001',
        ItemName: 'أكياس دم مفردة 450ml مع محلول CPDA-1',
        Quantity: 2000,
        Unit: 'كيس',
        BatchNumber: 'BTH-TRM-2026-A1',
        ExpiryDate: '2028-06-30',
        StorageType: 'ثلاجة',
        StorageLocation: 'ثلاجة حفظ أكياس الدم #1 - الرف A',
      },
      {
        ItemCode: 'ITM-002',
        ItemName: 'أكياس دم مزدوجة 450ml مع محلول حفظ SAGM',
        Quantity: 1000,
        Unit: 'كيس',
        BatchNumber: 'BTH-TRM-2026-A2',
        ExpiryDate: '2028-06-30',
        StorageType: 'ثلاجة',
        StorageLocation: 'ثلاجة حفظ أكياس الدم #2 - الرف B',
      },
    ],
  },
  {
    Id: 2,
    VoucherNumber: 'REC-2026-0002',
    PoNumber: 'PO-2026-9088',
    Date: '2026-08-01',
    Warehouse: 'مخزن المركز الإقليمي - بنغازي',
    SupplierName: 'شركة بيوتست الطبية (Biotest Medical)',
    SupplierCode: 'SUP-BIO-03',
    DelegateName: 'عمر ميلاد السويحلي',
    DelegatePhone: '0925566112',
    DelegateIdNumber: '119830987654',
    StorekeeperName: 'فاطمة علي - أمين المخزن',
    StorekeeperSignature: true,
    TotalQuantity: 500,
    Notes: 'استلام كواشف مخبرية مبردة مع مراقبة درجات الحرارة أثناء النقل',
    Status: 'معتمد',
    CreatedAt: '2026-08-01 11:15',
    Items: [
      {
        ItemCode: 'ITM-004',
        ItemName: 'كاشف فصيلة الدم Anti-A Monoclonal 10ml',
        Quantity: 250,
        Unit: 'زجاجة',
        BatchNumber: 'BTH-BIO-26-88',
        ExpiryDate: '2027-08-20',
        StorageType: 'ثلاجة',
        StorageLocation: 'ثلاجة الكواشف والمحاليل #1',
      },
      {
        ItemCode: 'ITM-005',
        ItemName: 'كاشف فصيلة الدم Anti-B Monoclonal 10ml',
        Quantity: 250,
        Unit: 'زجاجة',
        BatchNumber: 'BTH-BIO-26-89',
        ExpiryDate: '2027-08-20',
        StorageType: 'ثلاجة',
        StorageLocation: 'ثلاجة الكواشف والمحاليل #1',
      },
    ],
  },
  {
    Id: 3,
    VoucherNumber: 'REC-2026-0003',
    PoNumber: 'PO-2026-9112',
    Date: '2026-08-15',
    Warehouse: 'المخزن الرئيسي المركز - طرابلس',
    SupplierName: 'شركة بكتون ديكنسون (Becton Dickinson)',
    SupplierCode: 'SUP-BD-05',
    DelegateName: 'إبراهيم علي القماطي',
    DelegatePhone: '0917788443',
    DelegateIdNumber: '119910456789',
    StorekeeperName: 'أحمد محمد - أمين الخزينة',
    StorekeeperSignature: true,
    TotalQuantity: 1500,
    Notes: 'استلام وجبة إبر ومستلزمات جمع الدم للمخزن الجاف',
    Status: 'معتمد',
    CreatedAt: '2026-08-15 09:45',
    Items: [
      {
        ItemCode: 'ITM-007',
        ItemName: 'إبر سحب دم معقمة 16G مزودة بصمام أمان',
        Quantity: 1000,
        Unit: 'صندوق',
        BatchNumber: 'BTH-BD-26-44',
        ExpiryDate: '2029-01-01',
        StorageType: 'مخزن',
        StorageLocation: 'مخزن المستلزمات الجافة - الرف C',
      },
      {
        ItemCode: 'ITM-008',
        ItemName: 'قفازات طبية لاتكس معقمة بدون بودرة M (100 قطعة)',
        Quantity: 500,
        Unit: 'علبة',
        BatchNumber: 'BTH-BD-26-55',
        ExpiryDate: '2029-03-15',
        StorageType: 'مخزن',
        StorageLocation: 'مخزن الوقاية والسلامة - الرف A',
      },
    ],
  },
  {
    Id: 4,
    VoucherNumber: 'REC-2026-0004',
    PoNumber: 'PO-2026-9250',
    Date: '2026-09-10',
    Warehouse: 'المخزن الرئيسي المركز - طرابلس',
    SupplierName: 'شركة سيمنز الطبية للرعاية الصحية (Siemens Healthineers)',
    SupplierCode: 'SUP-SMZ-04',
    DelegateName: 'رمزي البشير الترهوني',
    DelegatePhone: '0926677889',
    DelegateIdNumber: '119880789012',
    StorekeeperName: 'أحمد محمد - أمين الخزينة',
    StorekeeperSignature: false,
    TotalQuantity: 800,
    Notes: 'الشحنة قيد التدقيق المخبري وفحص درجات الحرارة والتحقق من الكميات قبل الاعتماد النهائي',
    Status: 'قيد المراجعة',
    CreatedAt: '2026-09-10 11:00',
    Items: [
      {
        ItemCode: 'ITM-003',
        ItemName: 'أكياس دم ثلاثية 450ml مع مرشح فصل الصفائح',
        Quantity: 500,
        Unit: 'كيس',
        BatchNumber: 'BTH-TRM-2026-T3',
        ExpiryDate: '2028-08-15',
        StorageType: 'ثلاجة',
        StorageLocation: 'منطقة الفحص والاستلام المؤقت',
      },
      {
        ItemCode: 'ITM-006',
        ItemName: 'كاشف العامل الريزيسي Anti-D (Rh) 10ml',
        Quantity: 300,
        Unit: 'زجاجة',
        BatchNumber: 'BTH-BIO-26-90',
        ExpiryDate: '2027-09-10',
        StorageType: 'ثلاجة',
        StorageLocation: 'ثلاجة الاستلام المؤقت',
      },
    ],
  },
];

// =============================================
// 6. قائمة أذونات الصرف (المنصرف)
// =============================================
export const initialIssueVouchers: IssueVoucher[] = [
  {
    Id: 1,
    VoucherNumber: 'ISS-2026-0001',
    Date: '2026-07-28',
    Warehouse: 'المخزن الرئيسي المركز - طرابلس',
    BeneficiaryName: 'مصرف الدم المركزي - طرابلس (طريق الشط)',
    BeneficiaryType: 'مصرف دم مركزي',
    ReceiverName: 'طارق عبد السلام الزنتاني',
    ReceiverPhone: '0913344556',
    ReceiverIdNumber: '119850234190',
    StorekeeperName: 'أحمد محمد - أمين الخزينة',
    StorekeeperSignature: true,
    TotalQuantity: 400,
    Purpose: 'تزويد دوري لحملات التبرع بالدم المتنقلة والثابتة',
    Notes: 'تم تسليم الشحنة في سيارة مجهزة بوسائل التبريد المعتمدة',
    Status: 'معتمد',
    CreatedAt: '2026-07-28 12:00',
    Items: [
      {
        ItemCode: 'ITM-001',
        ItemName: 'أكياس دم مفردة 450ml مع محلول CPDA-1',
        Quantity: 300,
        Unit: 'كيس',
        BatchNumber: 'BTH-TRM-2026-A1',
        ExpiryDate: '2028-06-30',
        StorageType: 'ثلاجة',
        StorageLocation: 'ثلاجة حفظ أكياس الدم #1',
      },
      {
        ItemCode: 'ITM-004',
        ItemName: 'كاشف فصيلة الدم Anti-A Monoclonal 10ml',
        Quantity: 100,
        Unit: 'زجاجة',
        BatchNumber: 'BTH-BIO-26-88',
        ExpiryDate: '2027-08-20',
        StorageType: 'ثلاجة',
        StorageLocation: 'ثلاجة الكواشف والمحاليل #1',
      },
    ],
  },
  {
    Id: 2,
    VoucherNumber: 'ISS-2026-0002',
    Date: '2026-08-04',
    Warehouse: 'المخزن الرئيسي المركز - طرابلس',
    BeneficiaryName: 'بنك الدم - مركز سبها الطبي',
    BeneficiaryType: 'بنك دم فرعي',
    ReceiverName: 'مفتاح أحمد السليماني',
    ReceiverPhone: '0919988776',
    ReceiverIdNumber: '119840567890',
    StorekeeperName: 'أحمد محمد - أمين الخزينة',
    StorekeeperSignature: true,
    TotalQuantity: 350,
    Purpose: 'تزويد طارئ لاحتياجات بنك الدم بمدينة سبها',
    Notes: 'إذن صرف عاجل بناءً على برقية الاحتياج الطارئ',
    Status: 'معتمد',
    CreatedAt: '2026-08-04 14:20',
    Items: [
      {
        ItemCode: 'ITM-002',
        ItemName: 'أكياس دم مزدوجة 450ml مع محلول حفظ SAGM',
        Quantity: 150,
        Unit: 'كيس',
        BatchNumber: 'BTH-TRM-2026-A2',
        ExpiryDate: '2028-06-30',
        StorageType: 'ثلاجة',
        StorageLocation: 'ثلاجة حفظ أكياس الدم #2',
      },
      {
        ItemCode: 'ITM-007',
        ItemName: 'إبر سحب دم معقمة 16G مزودة بصمام أمان',
        Quantity: 200,
        Unit: 'صندوق',
        BatchNumber: 'BTH-BD-26-44',
        ExpiryDate: '2029-01-01',
        StorageType: 'مخزن',
        StorageLocation: 'مخزن المستلزمات الجافة',
      },
    ],
  },
  {
    Id: 3,
    VoucherNumber: 'ISS-2026-0003',
    Date: '2026-08-18',
    Warehouse: 'مخزن المركز الإقليمي - مصراتة',
    BeneficiaryName: 'مصرف الدم المركزي - مصراتة',
    BeneficiaryType: 'مصرف دم مركزي',
    ReceiverName: 'عبد الله الهادي الكواش',
    ReceiverPhone: '0917788990',
    ReceiverIdNumber: '119900345612',
    StorekeeperName: 'فاطمة علي - أمين المخزن',
    StorekeeperSignature: true,
    TotalQuantity: 100,
    Purpose: 'دعم مخزون كواشف الفصائل والمطابقة',
    Notes: 'تم الاستلام والتوقيع حسب الأصول',
    Status: 'معتمد',
    CreatedAt: '2026-08-18 10:10',
    Items: [
      {
        ItemCode: 'ITM-006',
        ItemName: 'كاشف العامل الريزيسي Anti-D (Rh) Monoclonal/Polyclonal 10ml',
        Quantity: 50,
        Unit: 'زجاجة',
        BatchNumber: 'BTH-MRK-26-10',
        ExpiryDate: '2027-08-15',
        StorageType: 'ثلاجة',
        StorageLocation: 'ثلاجة الكواشف',
      },
      {
        ItemCode: 'ITM-005',
        ItemName: 'كاشف فصيلة الدم Anti-B Monoclonal 10ml',
        Quantity: 50,
        Unit: 'زجاجة',
        BatchNumber: 'BTH-BIO-26-89',
        ExpiryDate: '2027-08-20',
        StorageType: 'ثلاجة',
        StorageLocation: 'ثلاجة الكواشف',
      },
    ],
  },
];

// =============================================
// 7. قائمة سجلات المواد التالفة (Damaged Goods)
// =============================================
export const initialDamagedItems: DamagedItemRecord[] = [
  {
    Id: 1,
    ItemCode: 'ITM-010',
    ItemName: 'محلول ملحي معقم Saline 0.9% 500ml',
    Quantity: 15,
    Unit: 'زجاجة',
    BatchNumber: 'BTH-BAX-12',
    ExpiryDate: '2026-06-01',
    Reason: 'انتهاء فترة الصلاحية المقررة',
    ReportNumber: 'DMG-2026-001',
    Date: '2026-06-15',
    RecordedBy: 'أحمد محمد - أمين الخزينة',
    Warehouse: 'المخزن الرئيسي المركز - طرابلس',
    DisposalStatus: 'تم الإتلاف',
  },
  {
    Id: 2,
    ItemCode: 'ITM-001',
    ItemName: 'أكياس دم مفردة 450ml مع محلول CPDA-1',
    Quantity: 12,
    Unit: 'كيس',
    BatchNumber: 'BTH-TRM-2025-OLD',
    ExpiryDate: '2026-05-20',
    Reason: 'تلف في الصمام وأنبوب السحب أثناء الشحن الأولي',
    ReportNumber: 'DMG-2026-002',
    Date: '2026-07-22',
    RecordedBy: 'أحمد محمد - أمين الخزينة',
    Warehouse: 'المخزن الرئيسي المركز - طرابلس',
    DisposalStatus: 'بانتظار الإتلاف',
  },
  {
    Id: 3,
    ItemCode: 'ITM-009',
    ItemName: 'أنابيب فحص الدم مع مانع تجلط EDTA K3 (100 أنبوب)',
    Quantity: 8,
    Unit: 'صندوق',
    BatchNumber: 'BTH-GRE-2024-X',
    ExpiryDate: '2026-07-10',
    Reason: 'كسر في العبوات الزجاجية الداخلية',
    ReportNumber: 'DMG-2026-003',
    Date: '2026-08-05',
    RecordedBy: 'فاطمة علي - أمين المخزن',
    Warehouse: 'مخزن المركز الإقليمي - بنغازي',
    DisposalStatus: 'معاينة',
  },
];

// =============================================
// 8. قائمة المستخدمين والأدوار
// =============================================
export const initialUsers: User[] = [
  {
    Id: 1,
    FullName: 'مدير عام المنظومة والنظام',
    Username: 'admin',
    Role: 'admin',
    RoleLabel: 'مدير النظام',
    Email: 'admin@blood-bank.gov.ly',
    Phone: '0910000001',
    Status: 'active',
    IsActive: true,
    CreatedAt: '2026-01-01',
    UpdatedAt: '2026-08-24',
    LastLogin: '2026-08-24 07:00',
    Warehouse: 'كافة المخازن المركزية والفرعية',
  },
  {
    Id: 2,
    FullName: 'د. سالم عبد الحميد الفيتوري',
    Username: 'treasury_manager',
    Role: 'treasury_manager',
    RoleLabel: 'مدير الخزينة والمخازن',
    Email: 'salem.fitouri@blood-bank.gov.ly',
    Phone: '0912233441',
    Status: 'active',
    IsActive: true,
    CreatedAt: '2026-01-10',
    UpdatedAt: '2026-08-20',
    LastLogin: '2026-08-23 15:30',
    Warehouse: 'المخزن الرئيسي المركز - طرابلس',
  },
  {
    Id: 3,
    FullName: 'أحمد محمد الصالح',
    Username: 'storekeeper_ahmed',
    Role: 'storekeeper',
    RoleLabel: 'أمين خزينة / مخزن (استلام وصرف)',
    Email: 'ahmed.saleh@blood-bank.gov.ly',
    Phone: '0923344552',
    Status: 'active',
    IsActive: true,
    CreatedAt: '2026-01-15',
    UpdatedAt: '2026-08-22',
    LastLogin: '2026-08-24 06:45',
    Warehouse: 'المخزن الرئيسي المركز - طرابلس',
  },
  {
    Id: 4,
    FullName: 'فاطمة علي الزروق',
    Username: 'storekeeper_fatima',
    Role: 'storekeeper',
    RoleLabel: 'أمين خزينة / مخزن (استلام وصرف)',
    Email: 'fatima.zarrouk@blood-bank.gov.ly',
    Phone: '0915566773',
    Status: 'frozen', // حساب مجمد
    IsActive: false,
    CreatedAt: '2026-02-01',
    UpdatedAt: '2026-08-10',
    LastLogin: '2026-08-09 11:20',
    Warehouse: 'مخزن المركز الإقليمي - بنغازي',
  },
  {
    Id: 5,
    FullName: 'محمد الطاهر السويحلي',
    Username: 'viewer_user',
    Role: 'viewer',
    RoleLabel: 'مراقب عام (عرض وتقارير)',
    Email: 'mohamed.t@blood-bank.gov.ly',
    Phone: '0937788994',
    Status: 'suspended', // حساب موقوف
    IsActive: false,
    CreatedAt: '2026-03-01',
    UpdatedAt: '2026-07-15',
    LastLogin: '2026-07-14 09:00',
    Warehouse: 'مخزن المركز الإقليمي - مصراتة',
  },
];
